### ISSUE TITLE
boost scipts help

### ISSUE THREAD

**Issue by liquidzym** [danoli3/apothecary-den#6]
hey,danoli,sorry to post here,can't find better place,not issue at all
need some help,can you point me out how to change the boost complied script can working with vs2013?  

cheers

**Comment by danoli3** [comment]
Hey @liquidzym, I have no idea how you would for VS, you might want to talk to @DomAmato

**Comment by arturoc** [comment]
they should work as they are if you have vs2013 installed instead of 2015

**Comment by liquidzym** [comment]
ok,i just added with --toolset=msvc-12.0,working fine,thxs
